# Generated by Django 3.0.10 on 2020-10-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
